### PR TITLE
Better support for Japanese

### PR DESCRIPTION
**Pull request by kshramt**

### CODE REVIEW

**Comment by ftilmann** [comment]
Is there a reason why you did not make this:
 my $word='(?:\p{Han}|\p{InHiragana}|\p{InKatakana}|[-\w\d*]|\\\\[\"\'\`~^][A-Za-z\*])+)';
The difference to your version (I think, have not tested) is that the above allows to merge latin, Han, Katakana and Hiragana in the same word whereas your version is limited to a single script (maybe that makes more sense and that was your intention).  
Also, would you have a little sample pair of files containing some Hiragana and Katakana that I can include into the testsuite (the files must be innocuous enough that you don't mind them being included in the repository)

**Comment by kshramt** [comment]
I force-pushed and updated this pull request.
As shown below, the latest version produces better diff than my previous version.

New:

```perl
my $word_ja='\p{Han}+|\p{InHiragana}+|\p{InKatakana}+';
my $word='(?:' . $word_ja . '|(?:(?:[-\w\d*]|\\\\[\"\'\`~^][A-Za-z\*])(?!(?:' . $word_ja . ')))+)';
```

kshramt_new

Previous:

```perl
my $word='(?:\p{Han}+|\p{InHiragana}+|\p{InKatakana}+|(?:[-\w\d*]|\\\\[\"\'\`~^][A-Za-z\*])+)';
```

kshramt_previous

Your suggestion:

Since Japanese words are not split by spaces, the regular expression you suggested could not produce a proper diff (some sentences are lost).

```perl
my $word='(?:\p{Han}|\p{InHiragana}|\p{InKatakana}|[-\w\d]|\\[\"\'`~^][A-Za-z\])+)';
```
ftilmann

# Test sources

- LuaTeXJa package should be installed
    - On Mac: `sudo port install texlive-lang-japanese` (http://trac.macports.org/wiki/TeXLivePackages)
- `lualatex` should be used instead of `pdflatex`

```bash
latexdiff --encoding=utf8 --type=CFONT ja1.tex ja2.tex > ja12.tex && lualatex ja12.tex && okular ja12.pdf
```

`ja1.tex`

```latex
\documentclass{ltjsarticle}

\begin{document}

例えばS波の到達時刻を知りたい場合，ジェフェリーズとブレンの掃除表が使えますか？

\end{document}
```

`ja2.tex`

```latex
\documentclass{ltjsarticle}

\begin{document}

例えばP波の到達時刻を知りたい場合，ジェフリーズとブレンの走時表が使えます．

\end{document}
```

**Comment by ftilmann** [comment]
Thanks, merged now except for changes to ../verify, where I would like to continue using pdflatex (ja-old,new.tex is in the testsuite directory now, to make it easier to include that later.

**Comment by ftilmann** [comment]
It turns out in the process of manually merging a conflict, and the commands surrounding this, the changes in your pull request now appear as if they were mine in the history.  I apologise for that; I am still in the process of getting my head around github and could not figure out the 'proper' procedure.  In any case I mention your user name as originator in the comments in the beginning of latexdiff source

**Comment by kshramt** [comment]
No problem. Thank you for including the patch!

**Pull request closed without merging**
